### ISSUE TITLE
Asgiref 2.0.1 version conflict

### ISSUE THREAD

**Issue by razerraz** [django/asgi_ipc#35]
Hi,

After upgrading stuff via pip, asgiref-2.0.1 was installed
asgi_ipc is the latest version as well : 1.4.2
Loading my project I got the error below
Obviously setup.py contains as dependency : asgiref~=1.1.2
`ERROR [celery.utils.dispatch.signal:276] Signal handler <bound method DjangoFixup.on_import_modules of <celery.fixups.django.DjangoFixup object at 0x757c89b0>> raised: ContextualVersionConflict(asgiref 2.0.1 (/usr/lib/python3.6/site-packages), Requirement.parse('asgiref~=1.1.2'), {'asgi-ipc'})
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/celery/utils/dispatch/signal.py", line 271, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/lib/python3.6/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/usr/lib/python3.6/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/usr/lib/python3.6/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/usr/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python3.6/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/usr/lib/python3.6/site-packages/channels/apps.py", line 14, in ready
    check_all()
  File "/usr/lib/python3.6/site-packages/channels/package_checks.py", line 22, in check_all
    module = importlib.import_module(package)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.6/site-packages/asgi_ipc/__init__.py", line 2, in <module>
    __version__ = pkg_resources.require('asgi_ipc')[0].version
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 875, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (asgiref 2.0.1 (/usr/lib/python3.6/site-packages), Requirement.parse('asgiref~=1.1.2'), {'asgi-ipc'})
`

**Comment by andrewgodwin** [comment]
How did you upgrade stuff via pip? `asgiref 2.0` is a future release that is not compatible with any of the current Channels packages, so you shouldn't just upgrade it independently - this is why the version is pinned like it is.

**Comment by razerraz** [comment]
I use python packages update website to check versions updates, then I create archlinux pkgbuilds with new versions. With AUR repository, this way all my machines are updated with the base distro upgrade tool yaourt.
I understand that my update method is not mandatory, but nothing in the asgiref description page (https://pypi.python.org/pypi/asgiref/2.0.1) inform that the release is a beta one. Maybe you should add some disclaimer about that fact in the description ?
Anyway thanks for your support
Cheers

**Comment by andrewgodwin** [comment]
It is not a beta release - it is just incompatible with the current version of `asgi_ipc`. If you are making packages for a distro, you should put the version dependencies into the package metadata so that the distribution's package manager knows this and will solve it correctly.

**Comment by razerraz** [comment]
Ok, understood. I just don't figure out the purpose of this stuff out of the channel usage, so excuse my ignorance
